apiVersion: v1
kind: Service
metadata:
  name: homefinder-search
  namespace: homefinder
spec:
  selector:
    app: homefinder-search
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
