apiVersion: v1
kind: Service
metadata:
  name: listing-search
  namespace: listing-search
spec:
  selector:
    app: listing-search
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
